### ISSUE TITLE
train 第4000的時候，都會爆GPU_MEM

### ISSUE THREAD

**Issue by ghost** [Luffy03/DCA#1]
謝謝你偉大的作品
目前嘗試執行你的MODEL，完全都沒改動，在執行時候，都會在4000時候中斷
顯示GPU的MEM不足，有點奇怪
如果不足的話，應該會在一開始就會出現，而不是繼續執行到4000才跳出來

另外，我想詢問一下，對於衛星影像或者的空拍照的segmentation，
除了DCA以外，您那邊有更好的MODEL或者有看過其他開源github有提供更好的training and predict這兩個功能
目前我找了很多，training功能都有，只是要test或predict自己的航空圖或衛星影像，就沒有提供了
最後真的很謝謝你，如果你有更棒的MODEL FOR segmentation，麻煩通知一下，謝謝

**Comment by Luffy03** [comment]
> 

1 在step4000时会加入target domain的数据进行训练，因此所需的显存会增加。这一点follow了LoveDA的设置，您可以再检查一下。

2 我没太理解您第二点的意思。我们的代码有提供predict的代码，在eval.py和my_test.py。如果您想要model的代码，现有的分割模型都可以集成到遥感图像和我们的代码中。

**Comment by ghost** [comment]
作者你好
目前我的GPU是3070
step4000會爆mem，不知道哪邊可以調整參數，可以降低使用GPU_MEM

我知道DCA有predict功能，只是跟你github其他model比，你有比較推哪個model嗎
我比較希望有農田跟森林的segmentation分類

謝謝你友善的回覆，給星星了

**Comment by Luffy03** [comment]
> 作者你好 目前我的GPU是3070 step4000會爆mem，不知道哪邊可以調整參數，可以降低使用GPU_MEM
> 
> 我知道DCA有predict功能，只是跟你github其他model比，你有比較推哪個model嗎 我比較希望有農田跟森林的segmentation分類
> 
> 謝謝你友善的回覆，給星星了
1 非常感谢您对我们工作的关注！
2 为节省显存，可以修改configs下torural.py或tourban.py中的batch_size。不过如果您想复现我们的结果，建议您使用更大的显存。
3 我们的工作是针对域适应问题的。对于农田和森林分割的话，我认为mmlab的mmsegmentation中提供的模型可以解决您的需求。

**Comment by Luffy03** [comment]
I will close this issue. Feel free to re-open it if you have any other questions about our work.
