### ISSUE TITLE
标签的维度

### ISSUE THREAD

**Issue by ghost89757** [Luffy03/DCA#2]
你好，我在训练一个批次得到的标签的维度是[batch_size, 512, 512, 3]，这影响了交叉熵的计算

**Comment by Luffy03** [comment]
> 你好，我在训练一个批次得到的标签的维度是[batch_size, 512, 512, 3]，这影响了交叉熵的计算

应该是读的标签为[512, 512, 3], 可以将标签转化为[512， 512]

**Comment by xjjj-hub** [comment]
は有効で、役に立つ
https://www.iqiyi.com/v_2g5a5i7gnyk.html




xj
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Luffy03/DCA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月24日(星期一) 晚上9:38
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [Luffy03/DCA] 标签的维度 (Issue #2)





  
你好，我在训练一个批次得到的标签的维度是[batch_size, 512, 512, 3]，这影响了交叉熵的计算
  
应该是读的标签为[512, 512, 3], 可以将标签转化为[512， 512]

**Comment by ghost89757** [comment]
> > 你好，我在训练一个批次得到的标签的维度是[batch_size, 512, 512, 3]，这影响了交叉熵的计算
> 
> 应该是读的标签为[512, 512, 3], 可以将标签转化为[512， 512]

已经解决了，谢谢
