### ISSUE TITLE
GPU利用率不高

### ISSUE THREAD

**Issue by jiuyuzhang** [Luffy03/DCA#3]
作者您好，我在训练时发现我的gpu利用率不高，然后主要卡在这一步，过程如下
/home/test/anaconda3/envs/dca/bin/python /home/test/桌面/DCA-master/DCA_train.py 
Use multi_layer!
INFO:ever.core.logger:ResNetEncoder: pretrained = True
INFO:data.nj:Dataset images: 1366
INFO:data.nj:Dataset images: 677
2023-11-20 19:07:56, INFO:MY:epochs ~= 58.829
  0%|          | 0/10001 [00:00<?, ?it/s]2023-11-20 19:08:28, INFO:MY:exp = ./log/DCA/2urban
2023-11-20 19:08:28, INFO:MY:iter = 0, total = nan, seg = 2.094, sour_intra = nan, lr = 0.000
  0%|          | 50/10001 [00:54<1:10:14,  2.36it/s]2023-11-20 19:08:51, INFO:MY:exp = ./log/DCA/2urban
2023-11-20 19:08:51, INFO:MY:iter = 50, total = 1.968, seg = 0.992, sour_intra = 0.977, lr = 0.001
  1%|          | 100/10001 [01:33<1:49:19,  1.51it/s]2023-11-20 19:09:29, INFO:MY:exp = ./log/DCA/2urban
2023-11-20 19:09:29, INFO:MY:iter = 100, total = 1.249, seg = 0.886, sour_intra = 0.363, lr = 0.001
  1%|▏         | 150/10001 [02:16<1:32:32,  1.77it/s]2023-11-20 19:10:13, INFO:MY:exp = ./log/DCA/2urban
2023-11-20 19:10:13, INFO:MY:iter = 150, total = 1.172, seg = 0.647, sour_intra = 0.526, lr = 0.002
  2%|▏         | 170/10001 [02:28<42:16,  3.88it/s]

  
   
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.108.03   Driver Version: 510.108.03   CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0  On |                  N/A |
| 30%   42C    P5    73W / 350W |  14497MiB / 24576MiB |     13%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1270      G   /usr/lib/xorg/Xorg                280MiB |
|    0   N/A  N/A      1905      G   /usr/bin/kwin_x11                  51MiB |
|    0   N/A  N/A      1909      G   /usr/bin/plasmashell               91MiB |
|    0   N/A  N/A      2575      G   ...RendererForSitePerProcess       75MiB |
|    0   N/A  N/A      2807      G   /usr/lib/firefox/firefox           20MiB |
|    0   N/A  N/A     10578      C   ...onda3/envs/dca/bin/python    13967MiB |
|    0   N/A  N/A     11348      G   ...ellTkcUjG.10.slave-socket        4MiB |
+-----------------------------------------------------------------------------+

观察到我使用的3090显卡gpu利用率最高为20%，请问我这是什么情况，谢谢

**Comment by Luffy03** [comment]
您好，首先非常感谢您关注我们的工作！
我还没有遇到过这个问题。请问您是否有将数据存放于固态硬盘呢？GPU利用率通常会跟io相关。。。

**Comment by jiuyuzhang** [comment]
好的感谢，我所使用的3090里面是机械硬盘，不是固态的，那应该是这个原因吧

**Comment by Luffy03** [comment]
> 好的感谢，我所使用的3090里面是机械硬盘，不是固态的，那应该是这个原因吧

是的，如果固态空间足够，还是尽量将数据放于固态。
