### ISSUE TITLE
License

### ISSUE THREAD

**Issue by maybenotilya** [Luffy03/DCA#5]
Hello again! We find your implementation cool and high quality and want to use it. But due to regional copyright laws we are not permitted to use it because it is not considered as open source software. You can read more about why license is important [here](https://opensource.com/article/23/1/why-sysadmins-should-license-code-open-source#:~:text=You%20have%20to%20make%20the,take%20advantage%20of%20your%20work.), for example. 
Please, add license file to your repository to help us avoid potential problems with law🥺 Thank you for youe patience!

**Comment by Luffy03** [comment]
Hi, sorry for not acknowledging that!
I have already created a new license file. Please check it!

**Comment by maybenotilya** [comment]
Great! Thank you a lot, have a nice day!
